# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Info(object):
    def setupUi(self, Info):
        Info.setObjectName("Info")
        Info.setWindowModality(QtCore.Qt.NonModal)
        Info.resize(600, 400)
        Info.setMinimumSize(QtCore.QSize(600, 400))
        Info.setMaximumSize(QtCore.QSize(600, 400))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        Info.setFont(font)
        Info.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("system/images/qq.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Info.setWindowIcon(icon)
        Info.setAutoFillBackground(False)
        Info.setStyleSheet("/* Author : Coahiming */\n"
"background-image: url(:/img/system/images/DataSci.png);")
        self.author = QtWidgets.QLabel(Info)
        self.author.setGeometry(QtCore.QRect(30, 50, 311, 40))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.author.setFont(font)
        self.author.setStyleSheet("color : white;font-size : 20px;background : transparent;")
        self.author.setAlignment(QtCore.Qt.AlignCenter)
        self.author.setObjectName("author")
        self.email = QtWidgets.QLabel(Info)
        self.email.setGeometry(QtCore.QRect(30, 230, 541, 40))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.email.setFont(font)
        self.email.setStyleSheet("color : white;font-size : 20px;background : transparent;")
        self.email.setAlignment(QtCore.Qt.AlignCenter)
        self.email.setObjectName("email")
        self.phone = QtWidgets.QLabel(Info)
        self.phone.setGeometry(QtCore.QRect(350, 49, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.phone.setFont(font)
        self.phone.setStyleSheet("color : white;font-size : 20px;background : transparent;")
        self.phone.setAlignment(QtCore.Qt.AlignCenter)
        self.phone.setObjectName("phone")
        self.SchoolNumber = QtWidgets.QLabel(Info)
        self.SchoolNumber.setGeometry(QtCore.QRect(30, 170, 541, 40))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.SchoolNumber.setFont(font)
        self.SchoolNumber.setStyleSheet("color : white;font-size : 20px;background : transparent;")
        self.SchoolNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.SchoolNumber.setObjectName("SchoolNumber")
        self.major = QtWidgets.QLabel(Info)
        self.major.setGeometry(QtCore.QRect(30, 110, 541, 40))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.major.setFont(font)
        self.major.setStyleSheet("color : white;font-size : 20px;background : transparent;")
        self.major.setAlignment(QtCore.Qt.AlignCenter)
        self.major.setObjectName("major")
        self.returnLogin = QtWidgets.QPushButton(Info)
        self.returnLogin.setGeometry(QtCore.QRect(140, 310, 311, 41))
        self.returnLogin.setStyleSheet("QPushButton{\n"
"    background: transparent;\n"
"    height:30px;\n"
"    color: white;\n"
"    border: 2px solid #FFFFFF;\n"
"    border-radius: 6px;\n"
"    font-size : 19px;\n"
"}\n"
"QPushButton:hover {\n"
"    /*background-color: #0000FF;*/\n"
"    \n"
"    border-radius: 6px;\n"
"    color:white;\n"
"    font-size : 20px;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    border: 2px solid rgb(80,80,80);\n"
"}")
        self.returnLogin.setObjectName("returnLogin")

        self.retranslateUi(Info)
        self.returnLogin.clicked.connect(Info.close)
        QtCore.QMetaObject.connectSlotsByName(Info)

    def retranslateUi(self, Info):
        _translate = QtCore.QCoreApplication.translate
        Info.setWindowTitle(_translate("Info", "作者信息"))
        self.author.setText(_translate("Info", "Author : Cao Haiming"))
        self.email.setText(_translate("Info", "E-mail : hoiming.wk@foxmail.com"))
        self.phone.setText(_translate("Info", "class : 计算机173"))
        self.SchoolNumber.setText(_translate("Info", "School : Shaanxi University of Science & Technology"))
        self.major.setText(_translate("Info", "Major : Computer Vision"))
        self.returnLogin.setText(_translate("Info", "返回"))
import icon_rc
import signup_rc
