# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.setWindowModality(QtCore.Qt.NonModal)
        login.resize(599, 518)
        login.setMinimumSize(QtCore.QSize(599, 518))
        login.setMaximumSize(QtCore.QSize(599, 518))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        login.setFont(font)
        login.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\system/images/qq.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        login.setWindowIcon(icon)
        login.setAutoFillBackground(False)
        login.setStyleSheet("/*Author : Caohaiming*/\n"
"#login{\n"
"background-image: url(:/lay/system/images/AI.jpeg);\n"
"}")
        self.Username_label = QtWidgets.QLabel(login)
        self.Username_label.setGeometry(QtCore.QRect(30, 250, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.Username_label.setFont(font)
        self.Username_label.setStyleSheet("color:white;background: transparent;\n"
"font-size : 18px;")
        self.Username_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Username_label.setLineWidth(1)
        self.Username_label.setScaledContents(False)
        self.Username_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Username_label.setObjectName("Username_label")
        self.Password_label = QtWidgets.QLabel(login)
        self.Password_label.setGeometry(QtCore.QRect(30, 320, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.Password_label.setFont(font)
        self.Password_label.setStyleSheet("color:white;background: transparent;\n"
"font-size : 20px;")
        self.Password_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Password_label.setObjectName("Password_label")
        self.Username = QtWidgets.QComboBox(login)
        self.Username.setGeometry(QtCore.QRect(110, 250, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setKerning(True)
        self.Username.setFont(font)
        self.Username.setStyleSheet("QComboBox{\n"
"        height: 30px;\n"
"        font-size : 25px;\n"
"       /* border-radius: 4px;*/\n"
"        background: transparent;\n"
"        border-color:#FFFFFF;\n"
"        border-style:solid;\n"
"        border-top-width:0px;\n"
"        border-right-width:0px;\n"
"        border-bottom-width:2px;\n"
"        border-left-width:0px;\n"
"}\n"
"QComboBox:enabled{\n"
"        color: white;\n"
"        font-size : 20px;\n"
"}\n"
"QComboBox:!enabled {\n"
"        color: rgb(80, 80, 80);\n"
"        font-size : 20px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"        background: transparent;\n"
"}\n"
"QComboBox::drop-down:hover {\n"
"        background: lightgrey;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        outline: none;\n"
"}")
        self.Username.setEditable(True)
        self.Username.setObjectName("Username")
        self.Password = QtWidgets.QLineEdit(login)
        self.Password.setGeometry(QtCore.QRect(110, 320, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.Password.setFont(font)
        self.Password.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Password.setAutoFillBackground(False)
        self.Password.setStyleSheet("QLineEdit{\n"
"        height: 30px;\n"
"        background: transparent;\n"
"}\n"
"QLineEdit:enabled {\n"
"        color:#FFFFFF;\n"
"        border-color:#FFFFFF;\n"
"        border-style:solid;\n"
"        border-top-width:0px;\n"
"        border-right-width:0px;\n"
"        border-bottom-width:2px;\n"
"        border-left-width:0px;\n"
"        color: white;\n"
"}\n"
"\n"
"QLineEdit:!enabled {\n"
"        color: rgb(80, 80, 80);\n"
"}")
        self.Password.setText("")
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password.setObjectName("Password")
        self.login_Button = QtWidgets.QPushButton(login)
        self.login_Button.setGeometry(QtCore.QRect(30, 390, 311, 41))
        self.login_Button.setStyleSheet("QPushButton{\n"
"    background: transparent;\n"
"    height:30px;\n"
"    color: white;\n"
"    border: 2px solid #FFFFFF;\n"
"    border-radius: 6px;\n"
"    font-size : 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #0000FF;\n"
"    \n"
"    border-radius: 6px;\n"
"    color:white;\n"
"    font-size : 22px;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    border-color : gray;\n"
"}")
        self.login_Button.setObjectName("login_Button")
        self.exit_button = QtWidgets.QPushButton(login)
        self.exit_button.setGeometry(QtCore.QRect(520, 210, 70, 70))
        self.exit_button.setMinimumSize(QtCore.QSize(70, 70))
        self.exit_button.setMaximumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.exit_button.setFont(font)
        self.exit_button.setStyleSheet("QPushButton{\n"
"    color :black;\n"
"    border-radius:35px;\n"
"    background :rgb(255,255,255);\n"
"    font-size : 22px;\n"
"    font-family : \"Microsoft YaHei\";\n"
"}\n"
"QPushButton:hover { \n"
"    font-size : 25px;\n"
"}\n"
"QPushButton:pressed {\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.exit_button.setObjectName("exit_button")
        self.signUpButton = QtWidgets.QPushButton(login)
        self.signUpButton.setGeometry(QtCore.QRect(350, 40, 90, 90))
        self.signUpButton.setMinimumSize(QtCore.QSize(90, 90))
        self.signUpButton.setMaximumSize(QtCore.QSize(90, 90))
        self.signUpButton.setStyleSheet("QPushButton{\n"
"    color :black;\n"
"    border-radius:45px;\n"
"    background :rgb(255,255,255);\n"
"    font-size : 28px;\n"
"    font-family : \"Microsoft YaHei\";\n"
"}\n"
"QPushButton:hover { \n"
"    font-size : 30px;\n"
"}\n"
"QPushButton:pressed { \n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.signUpButton.setObjectName("signUpButton")
        self.infoButton = QtWidgets.QPushButton(login)
        self.infoButton.setGeometry(QtCore.QRect(450, 120, 80, 80))
        self.infoButton.setMinimumSize(QtCore.QSize(80, 80))
        self.infoButton.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.infoButton.setFont(font)
        self.infoButton.setStyleSheet("QPushButton{\n"
"    color :black;\n"
"    border-radius:40px;\n"
"    background :rgb(255,255,255);\n"
"    font-size : 25px;\n"
"    font-family : \"Microsoft YaHei\";\n"
"}\n"
"QPushButton:hover { \n"
"    font-size : 28px;\n"
"}\n"
"QPushButton:pressed {\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.infoButton.setObjectName("infoButton")
        self.menu = QtWidgets.QFrame(login)
        self.menu.setGeometry(QtCore.QRect(0, 0, 600, 30))
        self.menu.setMinimumSize(QtCore.QSize(600, 30))
        self.menu.setMaximumSize(QtCore.QSize(600, 30))
        self.menu.setStyleSheet("QFrame{\n"
"    /*background: transparent;*/\n"
"    border-color:white;\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(0, 0, 0), stop:0.25 rgb(0, 0, 60),stop:0.50 rgb(0, 0, 120),stop:0.75 rgb(0, 0, 180),stop:1 rgb(0, 0, 255));\n"
"}")
        self.menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu.setObjectName("menu")
        self.closeButton = QtWidgets.QPushButton(self.menu)
        self.closeButton.setGeometry(QtCore.QRect(558, 0, 41, 29))
        self.closeButton.setMinimumSize(QtCore.QSize(29, 29))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.closeButton.setFont(font)
        self.closeButton.setStyleSheet("QPushButton{\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(0, 0, 0), stop:1 rgb(255, 255, 255));\n"
"    border: none;\n"
"    background : transparent;\n"
"    border-radius:1px;\n"
"}\n"
"/*悬停*/\n"
"QPushButton:hover {\n"
"    color: grey;\n"
"}\n"
"/*鼠标按下不放*/\n"
"QPushButton:pressed {\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.closeButton.setCheckable(False)
        self.closeButton.setAutoDefault(False)
        self.closeButton.setDefault(False)
        self.closeButton.setFlat(False)
        self.closeButton.setObjectName("closeButton")
        self.minButton = QtWidgets.QPushButton(self.menu)
        self.minButton.setGeometry(QtCore.QRect(520, -10, 41, 29))
        self.minButton.setMinimumSize(QtCore.QSize(29, 29))
        font = QtGui.QFont()
        font.setFamily("Webdings")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.minButton.setFont(font)
        self.minButton.setStyleSheet("QPushButton{\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(0, 0, 0), stop:1 rgb(255, 255, 255));\n"
"    border: none;\n"
"    background : transparent;\n"
"}\n"
"/*悬停*/\n"
"QPushButton:hover {\n"
"    color: grey;\n"
"}\n"
"/*鼠标按下不放*/\n"
"QPushButton:pressed {\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.minButton.setCheckable(False)
        self.minButton.setAutoDefault(False)
        self.minButton.setDefault(False)
        self.minButton.setFlat(False)
        self.minButton.setObjectName("minButton")

        self.retranslateUi(login)
        self.exit_button.clicked.connect(login.close)
        self.minButton.clicked.connect(login.showMinimized)
        self.closeButton.clicked.connect(login.close)
        self.signUpButton.clicked.connect(login.hide)
        self.infoButton.clicked.connect(login.hide)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "login"))
        self.Username_label.setText(_translate("login", "用户名"))
        self.Password_label.setText(_translate("login", "密码"))
        self.login_Button.setText(_translate("login", "登录"))
        self.exit_button.setText(_translate("login", "退出"))
        self.signUpButton.setText(_translate("login", "注册"))
        self.infoButton.setText(_translate("login", "关于"))
        self.closeButton.setText(_translate("login", "×"))
        self.minButton.setText(_translate("login", "0"))
import icon_rc
