# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1150, 870)
        Form.setMinimumSize(QtCore.QSize(900, 700))
        Form.setMaximumSize(QtCore.QSize(100000, 100000))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/lay/system/images/qq.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("/* Author : Caohaiming */\n"
"background-color: rgb(255, 255, 255);")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 30, 1150, 841))
        self.tabWidget.setMinimumSize(QtCore.QSize(900, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(10000, 10000))
        self.tabWidget.setMouseTracking(True)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setToolTipDuration(-1)
        self.tabWidget.setAccessibleName("")
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("QTabWidget::pane{\n"
"    border:none;\n"
"}\n"
"QTabWidget::tab-bar{\n"
"        alignment:up;\n"
"}\n"
"QTabBar::tab{\n"
"    background:transparent;\n"
"    /*color:white;*/\n"
"    /*min-width:30ex;\n"
"    min-height:10ex;*/\n"
"}\n"
"QTabBar::tab:hover{\n"
"    background:rgb(255, 255, 255);\n"
"}\n"
"QTabBar::tab:pressed{\n"
"    padding-left : 1px;\n"
"    padding-top : 1px;\n"
"}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(70, 70))
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.upLoadTab = QtWidgets.QWidget()
        self.upLoadTab.setStyleSheet("#upLoadTab{\n"
"background-image: url(:/img/system/images/DataSci.png);\n"
"}")
        self.upLoadTab.setObjectName("upLoadTab")
        self.SourceImage = QtWidgets.QLabel(self.upLoadTab)
        self.SourceImage.setGeometry(QtCore.QRect(10, 50, 561, 471))
        self.SourceImage.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(132, 132, 132);")
        self.SourceImage.setText("")
        self.SourceImage.setObjectName("SourceImage")
        self.NewImage = QtWidgets.QLabel(self.upLoadTab)
        self.NewImage.setGeometry(QtCore.QRect(580, 50, 561, 471))
        self.NewImage.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(132, 132, 132);")
        self.NewImage.setText("")
        self.NewImage.setObjectName("NewImage")
        self.textBrowser = QtWidgets.QTextBrowser(self.upLoadTab)
        self.textBrowser.setGeometry(QtCore.QRect(20, 570, 551, 181))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("/*background-color: rgb(255, 255, 255);*/\n"
"font: 12pt \"Cambria\";\n"
"/*border: 2px solid rgb(132, 132, 132);*/\n"
"background-color : transparent;\n"
"color : white;\n"
"border : None")
        self.textBrowser.setLineWidth(1)
        self.textBrowser.setObjectName("textBrowser")
        self.SourceLabel = QtWidgets.QLabel(self.upLoadTab)
        self.SourceLabel.setGeometry(QtCore.QRect(10, 10, 561, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.SourceLabel.setFont(font)
        self.SourceLabel.setStyleSheet("background-color : transparent;\n"
"color : white;\n"
"/*font-size : 20px;*/")
        self.SourceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SourceLabel.setObjectName("SourceLabel")
        self.DistImage = QtWidgets.QLabel(self.upLoadTab)
        self.DistImage.setGeometry(QtCore.QRect(580, 10, 561, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.DistImage.setFont(font)
        self.DistImage.setStyleSheet("background-color : transparent;\n"
"color : white;\n"
"/*font-size : 20px;*/")
        self.DistImage.setAlignment(QtCore.Qt.AlignCenter)
        self.DistImage.setObjectName("DistImage")
        self.SrcInfo = QtWidgets.QLabel(self.upLoadTab)
        self.SrcInfo.setGeometry(QtCore.QRect(20, 530, 551, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.SrcInfo.setFont(font)
        self.SrcInfo.setStyleSheet("background-color : transparent;\n"
"color : white;\n"
"/*font-size : 20px;*/")
        self.SrcInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.SrcInfo.setObjectName("SrcInfo")
        self.UpLoadButton = QtWidgets.QPushButton(self.upLoadTab)
        self.UpLoadButton.setGeometry(QtCore.QRect(580, 570, 261, 41))
        self.UpLoadButton.setStyleSheet("QPushButton{\n"
"    background: transparent;\n"
"    height:30px;\n"
"    color: white;\n"
"    border: 2px solid #FFFFFF;\n"
"    border-radius: 6px;\n"
"    font-size : 22px;\n"
"}\n"
"QPushButton:hover {\n"
"    /*background-color: #0000FF;*/\n"
"    \n"
"    border-radius: 6px;\n"
"    /*color:white;*/\n"
"    font-size : 24px;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    border: 2px solid rgb(80,80,80);\n"
"}")
        self.UpLoadButton.setObjectName("UpLoadButton")
        self.GenerateButton = QtWidgets.QPushButton(self.upLoadTab)
        self.GenerateButton.setGeometry(QtCore.QRect(880, 570, 261, 41))
        self.GenerateButton.setStyleSheet("QPushButton{\n"
"    background: transparent;\n"
"    height:30px;\n"
"    color: white;\n"
"    border: 2px solid #FFFFFF;\n"
"    border-radius: 6px;\n"
"    font-size : 22px;\n"
"}\n"
"QPushButton:hover {\n"
"    /*background-color: #0000FF;*/\n"
"    \n"
"    border-radius: 6px;\n"
"    /*color:white;*/\n"
"    font-size : 24px;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    border: 2px solid rgb(80,80,80);\n"
"}")
        self.GenerateButton.setObjectName("GenerateButton")
        self.SaveButton = QtWidgets.QPushButton(self.upLoadTab)
        self.SaveButton.setGeometry(QtCore.QRect(720, 710, 281, 41))
        self.SaveButton.setStyleSheet("QPushButton{\n"
"    background: transparent;\n"
"    height:30px;\n"
"    color: white;\n"
"    border: 2px solid #FFFFFF;\n"
"    border-radius: 6px;\n"
"    font-size : 22px;\n"
"}\n"
"QPushButton:hover {\n"
"    /*background-color: #0000FF;*/\n"
"    \n"
"    border-radius: 6px;\n"
"    /*color:white;*/\n"
"    font-size : 24px;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    border: 2px solid rgb(80,80,80);\n"
"}")
        self.SaveButton.setObjectName("SaveButton")
        self.UploadOpenAugmentationButton = QtWidgets.QPushButton(self.upLoadTab)
        self.UploadOpenAugmentationButton.setGeometry(QtCore.QRect(580, 640, 261, 41))
        self.UploadOpenAugmentationButton.setStyleSheet("QPushButton{\n"
"    background: transparent;\n"
"    height:30px;\n"
"    color: white;\n"
"    border: 2px solid #FFFFFF;\n"
"    border-radius: 6px;\n"
"    font-size : 22px;\n"
"}\n"
"QPushButton:hover {\n"
"    /*background-color: #0000FF;*/\n"
"    \n"
"    border-radius: 6px;\n"
"    /*color:white;*/\n"
"    font-size : 24px;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    border: 2px solid rgb(80,80,80);\n"
"}")
        self.UploadOpenAugmentationButton.setObjectName("UploadOpenAugmentationButton")
        self.UploadParameterSettingButton = QtWidgets.QPushButton(self.upLoadTab)
        self.UploadParameterSettingButton.setGeometry(QtCore.QRect(880, 640, 261, 41))
        self.UploadParameterSettingButton.setStyleSheet("QPushButton{\n"
"    background: transparent;\n"
"    height:30px;\n"
"    color: white;\n"
"    border: 2px solid #FFFFFF;\n"
"    border-radius: 6px;\n"
"    font-size : 22px;\n"
"}\n"
"QPushButton:hover {\n"
"    /*background-color: #0000FF;*/\n"
"    \n"
"    border-radius: 6px;\n"
"    /*color:white;*/\n"
"    font-size : 24px;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    border: 2px solid rgb(80,80,80);\n"
"}")
        self.UploadParameterSettingButton.setObjectName("UploadParameterSettingButton")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/maini/system/images/upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.upLoadTab, icon1, "")
        self.OCRTab = QtWidgets.QWidget()
        self.OCRTab.setStyleSheet("#OCRTab{\n"
"background-image: url(:/img/system/images/DataSci.png);\n"
"}")
        self.OCRTab.setObjectName("OCRTab")
        self.displayImage = QtWidgets.QLabel(self.OCRTab)
        self.displayImage.setGeometry(QtCore.QRect(10, 10, 1131, 631))
        self.displayImage.setStyleSheet("border: 2px solid rgb(132, 132, 132);")
        self.displayImage.setText("")
        self.displayImage.setObjectName("displayImage")
        self.CaptureButton = QtWidgets.QPushButton(self.OCRTab)
        self.CaptureButton.setGeometry(QtCore.QRect(590, 650, 250, 41))
        self.CaptureButton.setStyleSheet("QPushButton{\n"
"    background: transparent;\n"
"    height:30px;\n"
"    color: white;\n"
"    border: 2px solid #FFFFFF;\n"
"    border-radius: 6px;\n"
"    font-size : 22px;\n"
"}\n"
"QPushButton:hover {\n"
"    /*background-color: #0000FF;*/\n"
"    \n"
"    border-radius: 6px;\n"
"    /*color:white;*/\n"
"    font-size : 24px;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    border: 2px solid rgb(80,80,80);\n"
"}")
        self.CaptureButton.setObjectName("CaptureButton")
        self.detectButton = QtWidgets.QPushButton(self.OCRTab)
        self.detectButton.setGeometry(QtCore.QRect(890, 650, 250, 41))
        self.detectButton.setStyleSheet("QPushButton{\n"
"    background: transparent;\n"
"    height:30px;\n"
"    color: white;\n"
"    border: 2px solid #FFFFFF;\n"
"    border-radius: 6px;\n"
"    font-size : 22px;\n"
"}\n"
"QPushButton:hover {\n"
"    /*background-color: #0000FF;*/\n"
"    \n"
"    border-radius: 6px;\n"
"    /*color:white;*/\n"
"    font-size : 24px;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    border: 2px solid rgb(80,80,80);\n"
"}")
        self.detectButton.setObjectName("detectButton")
        self.AugmentButton = QtWidgets.QPushButton(self.OCRTab)
        self.AugmentButton.setGeometry(QtCore.QRect(890, 710, 250, 41))
        self.AugmentButton.setStyleSheet("QPushButton{\n"
"    background: transparent;\n"
"    height:30px;\n"
"    color: white;\n"
"    border: 2px solid #FFFFFF;\n"
"    border-radius: 6px;\n"
"    font-size : 22px;\n"
"}\n"
"QPushButton:hover {\n"
"    /*background-color: #0000FF;*/\n"
"    \n"
"    border-radius: 6px;\n"
"    /*color:white;*/\n"
"    font-size : 24px;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    border: 2px solid rgb(80,80,80);\n"
"}")
        self.AugmentButton.setObjectName("AugmentButton")
        self.ParameterSettingButton = QtWidgets.QPushButton(self.OCRTab)
        self.ParameterSettingButton.setGeometry(QtCore.QRect(590, 710, 250, 41))
        self.ParameterSettingButton.setStyleSheet("QPushButton{\n"
"    background: transparent;\n"
"    height:30px;\n"
"    color: white;\n"
"    border: 2px solid #FFFFFF;\n"
"    border-radius: 6px;\n"
"    font-size : 22px;\n"
"}\n"
"QPushButton:hover {\n"
"    /*background-color: #0000FF;*/\n"
"    \n"
"    border-radius: 6px;\n"
"    /*color:white;*/\n"
"    font-size : 24px;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    border: 2px solid rgb(80,80,80);\n"
"}")
        self.ParameterSettingButton.setObjectName("ParameterSettingButton")
        self.realtime_textBrowser = QtWidgets.QTextBrowser(self.OCRTab)
        self.realtime_textBrowser.setGeometry(QtCore.QRect(10, 650, 551, 101))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.realtime_textBrowser.setFont(font)
        self.realtime_textBrowser.setStyleSheet("/*background-color: rgb(255, 255, 255);*/\n"
"font: 12pt \"Cambria\";\n"
"/*border: 2px solid rgb(132, 132, 132);*/\n"
"background-color : transparent;\n"
"color : white;\n"
"border : None")
        self.realtime_textBrowser.setLineWidth(1)
        self.realtime_textBrowser.setObjectName("realtime_textBrowser")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\system/images/ocr.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.OCRTab, icon2, "")
        self.otherTab = QtWidgets.QWidget()
        self.otherTab.setStyleSheet("#otherTab{\n"
"background-image: url(:/img/system/images/DataSci.png);\n"
"}")
        self.otherTab.setObjectName("otherTab")
        self.FaceDisplayImage = QtWidgets.QLabel(self.otherTab)
        self.FaceDisplayImage.setGeometry(QtCore.QRect(10, 10, 1130, 691))
        self.FaceDisplayImage.setStyleSheet("border: 2px solid rgb(132, 132, 132);")
        self.FaceDisplayImage.setText("")
        self.FaceDisplayImage.setObjectName("FaceDisplayImage")
        self.FaceDetectButton = QtWidgets.QPushButton(self.otherTab)
        self.FaceDetectButton.setGeometry(QtCore.QRect(660, 710, 351, 41))
        self.FaceDetectButton.setStyleSheet("QPushButton{\n"
"    background: transparent;\n"
"    height:30px;\n"
"    color: white;\n"
"    border: 2px solid #FFFFFF;\n"
"    border-radius: 6px;\n"
"    font-size : 22px;\n"
"}\n"
"QPushButton:hover {\n"
"    /*background-color: #0000FF;*/\n"
"    \n"
"    border-radius: 6px;\n"
"    /*color:white;*/\n"
"    font-size : 24px;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    border: 2px solid rgb(80,80,80);\n"
"}")
        self.FaceDetectButton.setObjectName("FaceDetectButton")
        self.FaceCaptureButton = QtWidgets.QPushButton(self.otherTab)
        self.FaceCaptureButton.setGeometry(QtCore.QRect(110, 710, 351, 41))
        self.FaceCaptureButton.setStyleSheet("QPushButton{\n"
"    background: transparent;\n"
"    height:30px;\n"
"    color: white;\n"
"    border: 2px solid #FFFFFF;\n"
"    border-radius: 6px;\n"
"    font-size : 22px;\n"
"}\n"
"QPushButton:hover {\n"
"    /*background-color: #0000FF;*/\n"
"    \n"
"    border-radius: 6px;\n"
"    /*color:white;*/\n"
"    font-size : 24px;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    border: 2px solid rgb(80,80,80);\n"
"}")
        self.FaceCaptureButton.setObjectName("FaceCaptureButton")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(".\\system/images/other.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.otherTab, icon3, "")
        self.menu = QtWidgets.QFrame(Form)
        self.menu.setGeometry(QtCore.QRect(0, 0, 1150, 30))
        self.menu.setMinimumSize(QtCore.QSize(600, 30))
        self.menu.setMaximumSize(QtCore.QSize(10000, 30))
        self.menu.setStyleSheet("QFrame{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(0, 50, 0, 255), stop:0.05 rgba(0, 80, 0, 255), stop:0.36 rgba(0, 130, 0, 255), stop:0.6 rgba(0, 180, 0, 255), stop:0.75 rgba(0, 200, 0, 255), stop:0.79 rgba(0, 220, 0, 255), stop:0.86 rgba(0, 240, 0, 255), stop:0.935 rgba(0, 252, 0, 255));\n"
"}")
        self.menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu.setObjectName("menu")
        self.closeButton = QtWidgets.QPushButton(self.menu)
        self.closeButton.setGeometry(QtCore.QRect(1110, 0, 41, 29))
        self.closeButton.setMinimumSize(QtCore.QSize(29, 29))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.closeButton.setFont(font)
        self.closeButton.setStyleSheet("QPushButton{\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(0, 0, 0), stop:1 rgb(255, 255, 255));\n"
"    border: none;\n"
"    background : transparent;\n"
"    border-radius:1px;\n"
"}\n"
"/*悬停*/\n"
"QPushButton:hover {\n"
"    color: grey;\n"
"}\n"
"/*鼠标按下不放*/\n"
"QPushButton:pressed {\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.closeButton.setCheckable(False)
        self.closeButton.setAutoDefault(False)
        self.closeButton.setDefault(False)
        self.closeButton.setFlat(False)
        self.closeButton.setObjectName("closeButton")
        self.minButton = QtWidgets.QPushButton(self.menu)
        self.minButton.setGeometry(QtCore.QRect(1070, -10, 41, 29))
        self.minButton.setMinimumSize(QtCore.QSize(29, 29))
        font = QtGui.QFont()
        font.setFamily("Webdings")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.minButton.setFont(font)
        self.minButton.setStyleSheet("QPushButton{\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(0, 0, 0), stop:1 rgb(255, 255, 255));\n"
"    border: none;\n"
"    background : transparent;\n"
"}\n"
"/*悬停*/\n"
"QPushButton:hover {\n"
"    color: grey;\n"
"}\n"
"/*鼠标按下不放*/\n"
"QPushButton:pressed {\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.minButton.setCheckable(False)
        self.minButton.setAutoDefault(False)
        self.minButton.setDefault(False)
        self.minButton.setFlat(False)
        self.minButton.setObjectName("minButton")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.closeButton.clicked.connect(Form.close)
        self.minButton.clicked.connect(Form.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cambria\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.SourceLabel.setText(_translate("Form", "Source Image"))
        self.DistImage.setText(_translate("Form", "Target Image"))
        self.SrcInfo.setText(_translate("Form", "Parameter Information"))
        self.UpLoadButton.setText(_translate("Form", "上传"))
        self.GenerateButton.setText(_translate("Form", "生成标记图像"))
        self.SaveButton.setText(_translate("Form", "保存生成结果"))
        self.UploadOpenAugmentationButton.setText(_translate("Form", "图像增强开启"))
        self.UploadParameterSettingButton.setText(_translate("Form", "参数设置"))
        self.CaptureButton.setText(_translate("Form", "摄像头开启"))
        self.detectButton.setText(_translate("Form", "实时检测开启"))
        self.AugmentButton.setText(_translate("Form", "图像增强开启"))
        self.ParameterSettingButton.setText(_translate("Form", "参数设置"))
        self.realtime_textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cambria\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.FaceDetectButton.setText(_translate("Form", "实时检测开启"))
        self.FaceCaptureButton.setText(_translate("Form", "摄像头开启"))
        self.closeButton.setText(_translate("Form", "×"))
        self.minButton.setText(_translate("Form", "0"))
import icon_rc
import main_rc
import signup_rc
